### ISSUE TITLE
Dependency issue when installing hanami-bootstrap.

### ISSUE THREAD

**Issue by sirhopcount** [davydovanton/lotus-bootstrap#4]
Hi,

I tried installing hanami-bootstrap but got a dependency error when running bundle.  Apparently hanami (0.8) depends on  hanami-assets 0.3 but hanami-bootstrap depends on 0.2.1.

My Gemfile (shortened): 

```
$ cat Gemfile 
source 'https://rubygems.org'

gem 'bundler'
gem 'rake'
gem 'hanami',       '~> 0.8'
gem 'hanami-model', '~> 0.6'
gem 'hanami-bootstrap'
...
```

Bundle install output:

```
$ bundle 
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "hanami-assets":
  In Gemfile:
    hanami (~> 0.8) was resolved to 0.8.0, which depends on
      hanami-assets (~> 0.3)

    hanami-bootstrap was resolved to 0.2.0, which depends on
      hanami-assets (~> 0.2.1)
```

**Comment by alejandrobabio** [comment]
hi @sirhopcount,

This issue is fixed here, but not yet published at rubygems. In the meanwhile, you can use the git version at your Gemfile.

```
gem 'hanami-bootstrap', git: 'git://github.com/davydovanton/hanami-bootstrap.git'
```

**Comment by sirhopcount** [comment]
Thanks, any idea when the gem is going to updated?

**Comment by davydovanton** [comment]
@sirhopcount hello, sorry for long response, I had vacation. I'll update this gem ASAP.
Thanks!

**Comment by davydovanton** [comment]
hello again,
I [pushed](https://rubygems.org/gems/hanami-bootstrap) new version of gem to rubygems 🎉 
Guys, could you check your applications ?

**Comment by sirhopcount** [comment]
I just tested it and works like charm, closing the issue.
